### ISSUE TITLE
No module name corsheaders

### ISSUE THREAD

**Issue by jitendravarma** [fafadiatech/newscout_web#221]
Steps to reproduce,
1. Clone or fork this repo
2. Install all the dependencies for pip
3. Create db 
Then, make migrations, it shows this error
```python
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/jitendravarma/Installs/envs/ns/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/jitendravarma/Installs/envs/ns/lib/python3.7/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/Users/jitendravarma/Installs/envs/ns/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/jitendravarma/Installs/envs/ns/lib/python3.7/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/Users/jitendravarma/Installs/envs/ns/lib/python3.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/jitendravarma/Installs/envs/ns/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders'
```
Fixed by doing
```sh
pip install django-cors-headers
```

**Comment by yspanchal** [comment]
Issue Fixed. https://github.com/fafadiatech/newscout_web/pull/265
